name = "Create Aeronautics Modpack"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac2b67d8bb81d073ca9489924513fb0f644b8eaa643765d6aff13c783c23d0e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
