name = "Create Aeronautics Modpack"
author = "PGSCOM"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60cc24ff8a8e80856598228068876deb1a1f81d6b8cfc605f6b903aa7e3c4350"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
