name = "Create Aeronautics Modpack"
author = "PGSCOM"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e53d88535379762b60bbef100076622a0205e68ddda3fb0d6db83b4d4dd3b8a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
